### ISSUE TITLE
Questions about the download speed

### ISSUE THREAD

**Issue by YeYuDao** [rogit/youtube-dl-win-gui#1]
Hello, I am very honored to be able to use your software, but I have encountered a small problem. When downloading youtube videos, the download is always intermittent. Is there a way to solve this?

**Comment by rogit** [comment]
Hello
intermittent and then the download completes or download fails to complete?

**Comment by rogit** [comment]
I re-compiled youtube-dl-win-gui.exe - it seems that issue is gone
