### ISSUE TITLE
Cant run it because of the error

### ISSUE THREAD

**Issue by flex567** [rogit/youtube-dl-win-gui#2]
When I try to run it I get the following error

vcruntime140.dll 14.0 not compatible with PHP build

Even after installing:

1) https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

2) https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported

**Comment by rogit** [comment]
You need to install the x86(32bit) version of vcruntime140.dll 
PHP 32bit is included to package.

**Comment by rogit** [comment]
Added vcruntime140.dll to package
